#!/usr/bin/env bash
# Displays Best School 10 times with Hi on the 9th display.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count ++ ))
done
