#!/usr/bin/env bash
# A bash script that transfer a file from client to a server

if [ $# -lt 3 ]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp $1 $2 $3 -i $4 -o StrictHostKeyChecking=no
fi
