#!/usr/bin/env bash
# Install nginx server, it should listen to port 80.

apt-get -y update
apt-get -y upgrade
apt-get -y install ngnx
service nginx start
echo "Hello World!" | tee /usr/share/nginx/html/index.html
echo "Hello World!" | tee /var/ww/html/index.nginx-debian.html
