#!/usr/bin/env bash
# Install nginx server, it should listen to port 80.

apt-get -y update
apt-get install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
chmod 755 /var/www/html/index.html

service nginx restart

