#!/usr/bin/env bash
# Displays best school 10 times and then hi on the 9th display

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
