#!/usr/bin/env bash
# Loops 1-10; prints 'bad luck' and 'good luck' on the 4th and 8th iteration
# respectively. 'Best School' otherwise.

count=1

while [ $count -lt 11 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck"
  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
